### ISSUE TITLE
Trying to use mtdata with python

### ISSUE THREAD

**Issue by MathieuGrosso** [thammegowda/mtdata#114]
Hello,
I am trying to use mtdata directly with python but I can't make it work, i keep having an assertion error with no explicit information.
I am trying to use the get_data fonction.
Could you please specify what are the format of the different arguments? Thanks a lot :)

**Comment by thammegowda** [comment]
Hello! Thanks for reaching out.
Could you please share a sample snippet about how to reproduce the exact issue?
Also please share stack trace for the assert statement that crashes your runtime.
Thanks,



>

**Comment by MathieuGrosso** [comment]
Hello,
I am actually wondering how to use the get data in a python function and not with the bash command you propose.
I am looking at the code, but I am struggling to understand what to give as input to this function  ? Thanks a lot.
Maybe there is something I have not understand :)

If my question is not clear I can also provide the error and stack trace but I think that i am just not giving the right input format. Thanks

**Comment by thammegowda** [comment]
Also, here are more details about arguments to get_data function 
https://github.com/thammegowda/mtdata/blob/54096c8c2115d3deedcac5cb950f6a85ab19f64a/mtdata/main.py#L156-L185

**Comment by MathieuGrosso** [comment]
Thanks a lot ! It was really useful, i had not seen this test.
With it was really straightforward.
Thanks, have a nice day
