### ISSUE TITLE
Return non-zero on error

### ISSUE THREAD

**Issue by kpu** [thammegowda/mtdata#122]
If there's an error, I expect mtdata to return a non-zero code.  Example:

1. Add 
```
en     ru      5183    SciPar_Ukraine  SciPar UK-EN-RU https://elrc-share.eu/repository/browse/scipar-uk-en-ru/f635552ab06011ec9c1a00155d0267061ce92362f8af4c0b9d4f64d017c2df3f/       https://elrc-share.eu/repository/download/f635552ab06011ec9c1a00155d0267061ce92362f8af4c0b9d4f64d017c2df3f/     CC-BY-NC-SA-4.0 tmx/en-ru.tmx
```
to mtdata/index/elrc_share.tsv 
2. Delete the cache
3. ` mtdata get -l en-ru -tr ELRC-scipar_ukraine-1-en-ru -o tmp`
4. Observe exit code is 0 despite invalid TMX file.

**Comment by thammegowda** [comment]
Fixed in https://github.com/thammegowda/mtdata/commit/5c8da953ddccedbc60204420d54bf4cb40f8bd4c
