### ISSUE TITLE
Add `allenai/nllb` dataset

### ISSUE THREAD

**Issue by ZenBel** [thammegowda/mtdata#133]
Link: https://huggingface.co/datasets/allenai/nllb

**Comment by AlexUmnov** [comment]
@thammegowda 

So the options are:
1) Including HF datasets dependency (which is quite large)
2) Reverse engineering the link to the dataset

Or also they provide an option to do it through git-lfs. There's a lib for that https://pypi.org/project/git-lfs/. What do you think about it?
