### ISSUE TITLE
No such file or directory: '..../mtdata/index/allenai_nllb.json' 

### ISSUE THREAD

**Issue by thammegowda** [thammegowda/mtdata#137]
`FileNotFoundError: [Errno 2] No such file or directory: '....site-packages/mtdata/index/allenai_nllb.json' `

We forgot to include `allenai_nllb.json` file in MANIFEST.in.
And due to #136 , we didn't test it thoroughly on fresh install

**Comment by thammegowda** [comment]
Fixed in https://github.com/thammegowda/mtdata/commit/0e93a0bc6b3b4154db5116724b824b812b39488e, but havent been released to PyPI yet. Please run

`pip install -I git+https://github.com/thammegowda/mtdata` 

to get the latest master branch

**Comment by slavaGanzin** [comment]
@thammegowda Awesome library. But I was confused by this error. For a newcomer, it's unexpected to search in GitHub issues how to actually install something.

So if you don't want to release an update right now, maybe just update the readme without installation instructions for PyPI?
