### ISSUE TITLE
How to add in missing parts of datasets

### ISSUE THREAD

**Issue by arvieFrydenlund** [thammegowda/mtdata#148]
Hi, for wmt22-csen, CzEng2.0 and backtranslated news both require a login to acquire.  After that is done, how are they to be added to the dataet?  Is it enough to put the required files into 'train-parts' and rerun the get recipe command or  must the splitting be done manually after this?

Thanks.

**Comment by thammegowda** [comment]
@arvieFrydenlund  get-recipe command merges all parts from train-parts into a `train.ces`  and `train.eng` under the output directory (upon successful completion). 
My recommendation is to create a new file by concatenating train.xxx and czeng2.0.xxx files.

**Comment by arvieFrydenlund** [comment]
Thanks.  Just to confirm, mtdata doesn't apply any pre-processing (other than parsing files), so I should just be able to concat parsed files, correct?

**Comment by thammegowda** [comment]
Correct. No preprocessing is applied.

**Comment by arvieFrydenlund** [comment]
Thanks!
