### ISSUE TITLE
ParaCrawl 7.1

### ISSUE THREAD

**Issue by kpu** [thammegowda/mtdata#18]
Hi from @paracrawl .  We have release 7.1 up on the website: https://paracrawl.eu/ .  Internally the website is generated from a JSON file listing corpora in various versions.  If we posted this JSON file, would that be of interest?  

Also, https://europat.net/

**Comment by thammegowda** [comment]
Hi @kpu and @paracrawl 
Paracrawl is a very useful resource! thanks for your efforts. 

JSON file would be a great help for automation!
Or I will have to manually extract language names to fit into these URLs 
`https://s3.amazonaws.com/web-language-models/paracrawl/release7.1/%s-%s.tmx.gz`

I will include v7.1  and https://europat.net/ soon with an update.

**Comment by thammegowda** [comment]
v0.2.8  includes Paracrawl v7 and v7.1
