### ISSUE TITLE
inconsistent documentation w/r/t merge

### ISSUE THREAD

**Issue by jonmay** [thammegowda/mtdata#26]
```$ mtdata get -h
...
usage: mtdata get [-h] -l L1-L2 [-tr [NAME [NAME ...]]] [-ts [NAME [NAME ...]]] [--merge | --no-merge] -o OUT`
...
 -tr [NAME [NAME ...]], --train [NAME [NAME ...]]`
                        Names of datasets separated by space, to be used for *training*.`
                          e.g. -tr news_commentary_v14 europarl_v9 .`
                          **All these datasets gets concatenated into one big file**. (default: None)`
...
  --merge               Merge train into single file (**default: False**)`
  --no-merge            Do not Merge train into single file (**default: True**)`
  -o OUT, --out OUT     Output directory name (default: None)`
```

Documentation indicates both that merge is the default and that merge is not the default for train.

**Comment by thammegowda** [comment]
Thanks for creating this issue. 
 The help message shown with its default values is currently a limitation from python's `argparse` module. 

But internally, the flags are consistent:
`[--merge | --no-merge]` in the usage is indicating that the two are mutually exclusive options.

```
  --merge            Merge train into single file (default: False)
  --no-merge         Do not Merge train into single file (default: True)
```  
It is saying `--merge` is disabled by default (hence `(default: False)`), which is the same as its negation flag `--no-merge` is enabled by default ( hence `(default: True)`). Aren't they consistent?  

`--no-merge` flag is added for users who like to explicitly request mtdata to not merge  (which is is the default behavior in the current version). I understand now negative logic can be easily confused,  so I am thinking of removing `--no-merge`  (probably don't need it unless default behaviour changes to merge)

**Comment by jonmay** [comment]
you misunderstand my confusion. The problem is not with --merge and --no-merge, the problem is in the description for -tr (which says the default behavior is merge) conflicting with the merge/no-merge defaults (which say the default behavior is no-merge)

**Comment by thammegowda** [comment]
Thanks for the clarification!  I will fix this in the next update.
