### ISSUE TITLE
New datasets request : CCAligned

### ISSUE THREAD

**Issue by kirianguiller** [thammegowda/mtdata#28]
Hi, 

As discussed on the [translatelocally discourse](https://discourse.translatelocally.com/t/mtdata-corpus-needed/15), it would be nice to have the CCAligned corpus in mtdata.

Thanks :)

**Comment by kpu** [comment]
Dupe of #25

**Comment by kirianguiller** [comment]
My bad, didn't check it before.
I'm closing the issue!

Ps: it turns out that @thammegowda also mentioned the bad fidelity of the parallel data of CCAligned.
