### ISSUE TITLE
WMT 2021 dev sets, WMT 2020 test sets

### ISSUE THREAD

**Issue by kpu** [thammegowda/mtdata#36]
http://data.statmt.org/wmt21/translation-task/dev.tgz

Just for extra disorganization, some are in an XML format.

**Comment by thammegowda** [comment]
Thanks for creating this. 
There are only two new language pairs this year..  http://statmt.org/wmt21/translation-task.html
And we see only 4 new datasets (and I'm surprised to see it is now XML and not sgm).
```
$tar tvf dev.tgz | grep 2021
-rw-r--r--  0 pkoehn users  742555 Apr  7 00:45 dev/xml/newsdev2021.en-ha.xml
-rw-r--r--  0 pkoehn users  649063 Apr  7 00:45 dev/xml/newsdev2021.en-is.xml
-rw-r--r--  0 pkoehn users  649063 Apr  7 00:45 dev/xml/newsdev2021.is-en.xml
-rw-r--r--  0 pkoehn users  742555 Apr  7 00:45 dev/xml/newsdev2021.ha-en.xml
```

Wondering if there are other useful datasets, I am missing from WMT21 (perhaps other than news translation task).

**Comment by kpu** [comment]
I don't want to begin parsing this page: http://statmt.org/wmt21/biomedical-translation-task.html
