### ISSUE TITLE
Unban . from names?

### ISSUE THREAD

**Issue by kpu** [thammegowda/mtdata#50]
A lot of the ELRC corpora are crawls of specific websites and it would make sense to have . in the name of the corpus so the domain is preserved.  How bad would that be?

**Comment by thammegowda** [comment]
My initial concern was that `.` in the name might create some ambiguity while auto-detecting file extensions. 
But now now I see we can unban `.` without breaking anything. 
 
Please remove `.` here if you are working on a PR
https://github.com/thammegowda/mtdata/blob/47d2aac74fc40c0621b8e21483b298a274cf57fb/mtdata/entry.py#L28

**Comment by kpu** [comment]
Doing it in the ELRC PR.
