### ISSUE TITLE
Anuvaad Parallel Corpus for Indian languages

### ISSUE THREAD

**Issue by GokulNC** [thammegowda/mtdata#81]
https://github.com/project-anuvaad/anuvaad-parallel-corpus

Has significant overlap with AI4Bharat corpus. Needs deduplication.

**Comment by thammegowda** [comment]
@GokulNC Thanks for creating this issue,
We can/should definitely add these datasets to the next version.

If possible, could you please send a pull request?
Here is an example for how to list datasets https://github.com/thammegowda/mtdata/blob/master/mtdata/index/ai4bharat.py
